# Usa la URL de conexión Direct Connection de Supabase (puerto 5432 o 6543)
spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.onelounmxkpycurnjnxc
spring.datasource.password=centro-medico

# Driver y Dialecto de PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Gestión de tablas automáticas
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true